<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SmartLost.BuildingBlocks.Core/SmartLost.BuildingBlocks.Core.csproj" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>
</Project>
